import customtkinter
def oprimir_boton(app,P):
    texto = P.get("0.0","end")
    print(texto)
    app.destroy()
def añadir_mascota():
    app = customtkinter.CTk()
    app.title("Gestion de mascotas")
    app.geometry('250x620')
    customtkinter.set_appearance_mode("dark")
    customtkinter.set_default_color_theme("green")
    label = customtkinter.CTkLabel(app,text="Ingrese el nombre de su mascota")
    label.grid(row=0, column=0, padx=0, pady=0, columnspan=2)
    P = customtkinter.CTkTextbox(app,width=150,height=30)
    P.grid(row=1, column=0, padx=20, pady=20, columnspan=2)
    label2 = customtkinter.CTkLabel(app,text="Ingrese la especie de su mascota")
    label2.grid(row=2, column=0, padx=0, pady=0, columnspan=2)
    P2 = customtkinter.CTkTextbox(app,width=150,height=30)
    P2.grid(row=3, column=0, padx=20, pady=20, columnspan=2)
    label3 = customtkinter.CTkLabel(app,text="Ingrese la raza de su mascota")
    label3.grid(row=4, column=0, padx=0, pady=0, columnspan=2)
    P3 = customtkinter.CTkTextbox(app,width=150,height=30)
    P3.grid(row=5, column=0, padx=20, pady=20, columnspan=2)
    label4 = customtkinter.CTkLabel(app,text="Ingrese el genero de su mascota")
    label4.grid(row=6, column=0, padx=0, pady=0, columnspan=2)
    P4 = customtkinter.CTkCheckBox(app,width=150,height=30,text="Masculino")
    P4.grid(row=7, column=0, padx=20, pady=20, columnspan=2)
    P42 = customtkinter.CTkCheckBox(app,width=150,height=30,text="Femenino")
    P42.grid(row=8, column=0, padx=0, pady=0, columnspan=2)
    label5 = customtkinter.CTkLabel(app,text="Ingrese la edad de su mascota")
    label5.grid(row=9, column=0, padx=0, pady=20, columnspan=2)
    P5 = customtkinter.CTkTextbox(app,width=150,height=30)
    P5.grid(row=10, column=0, padx=20, pady=20, columnspan=2)
    button = customtkinter.CTkButton(app, text="aceptar", command=lambda:oprimir_boton(app,P))
    button.grid(row=11, column=0, padx=50, pady=0, columnspan=2)
    app.mainloop()