import customtkinter
lista_genero = ["FEMENINO","MASCULINO"]
lista_vacunas = ["Tiene todas las vacunas","Tiene algunas vacunas","No tiene vacunas"]
def oprimir_boton(app,P):
    texto = P.get("0.0","end")
    print(texto)
    app.destroy()
def añadir_mascota():
    app = customtkinter.CTk()
    app.title("Gestion de mascotas")
    app.geometry('500x820')
    customtkinter.set_appearance_mode("dark")
    customtkinter.set_default_color_theme("green")
    label = customtkinter.CTkLabel(app,text="Ingrese el nombre de su mascota")
    label.grid(row=0, column=0, padx=0, pady=0)
    P = customtkinter.CTkTextbox(app,width=150,height=30)
    P.grid(row=1, column=0, padx=20, pady=20)
    label2 = customtkinter.CTkLabel(app,text="Ingrese la especie de su mascota")
    label2.grid(row=2, column=0, padx=0, pady=0)
    P2 = customtkinter.CTkTextbox(app,width=150,height=30)
    P2.grid(row=3, column=0, padx=20, pady=20)
    label3 = customtkinter.CTkLabel(app,text="Ingrese la raza de su mascota")
    label3.grid(row=4, column=0, padx=0, pady=0)
    P3 = customtkinter.CTkTextbox(app,width=150,height=30)
    P3.grid(row=5, column=0, padx=20, pady=20)
    label4 = customtkinter.CTkLabel(app,text="Ingrese el genero de su mascota")
    label4.grid(row=6, column=0, padx=0, pady=0)
    P4 = customtkinter.CTkComboBox(app,width=150,height=30,values=lista_genero)
    P4.grid(row=7, column=0, padx=20, pady=20)
    label5 = customtkinter.CTkLabel(app,text="Ingrese la edad de su mascota")
    label5.grid(row=8, column=0, padx=0, pady=20)
    P5 = customtkinter.CTkTextbox(app,width=150,height=30)
    P5.grid(row=9, column=0, padx=20, pady=20)
    label6 = customtkinter.CTkLabel(app,text="Ingrese nombre de la dieta de su mascota")
    label6.grid(row=0, column=1, padx=20, pady=20)
    P6 = customtkinter.CTkTextbox(app,width=150,height=30)
    P6.grid(row=1, column=1, padx=20, pady=20)
    label7 = customtkinter.CTkLabel(app,text="Ingrese el lugar de residencia de su mascota")
    label7.grid(row=2, column=1, padx=0, pady=20)
    P7 = customtkinter.CTkTextbox(app,width=150,height=30)
    P7.grid(row=3, column=1, padx=20, pady=20)
    label8 = customtkinter.CTkLabel(app,text="Ingrese si su mascota tiene las vacunas")
    label8.grid(row=4, column=1, padx=0, pady=20)
    P8 = customtkinter.CTkComboBox(app,width=150,height=30,values=lista_vacunas)
    P8.grid(row=5, column=1, padx=20, pady=20)
    button = customtkinter.CTkButton(app, text="aceptar", command=lambda:oprimir_boton(app,P))
    button.grid(row=6, column=1, padx=50, pady=0)
    app.mainloop()